# Generated by Django 3.1.5 on 2021-01-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210105_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
