# Generated by Django 3.1.5 on 2021-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20210105_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
