# Generated by Django 3.1.5 on 2021-01-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20210105_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cv',
            field=models.FileField(null=True, upload_to='resume/static/file'),
        ),
    ]
